version: "3.9"

services:
  postgres:
    container_name: nest-clean-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nestcleandb
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
  cache:
    container_name: nest-clean-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
